# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
import main as tt
import random
import sys

count = 0

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Get the screen resolution
        screen_resolution = QtWidgets.QApplication.desktop().screenGeometry()
        width, height = screen_resolution.width(), screen_resolution.height()
        # Set the window size
        MainWindow.resize(width, height)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        MainWindow.setObjectName("MainWindow")

   


        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(width/2-width/6, height/2-height/4, width/2, height/8))
        self.label.setStyleSheet(
"font: 36pt \"Segoe UI\";\n"
"")
        self.label.setObjectName("label")

        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(width/2-width/4, height/2-height/8, width/2, height/8))
        self.label2.setStyleSheet(
"font: 50pt \"Segoe UI\";\n"
"")
        self.label2.setObjectName("label2")


        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(width/2-width/4, height/2+height/8, width/2, height/8))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.onButtonClick)
        self.pushButton.setStyleSheet(

"font: 50pt \"Segoe UI\";\n""")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome to MoveSync"))
        self.label2.setText(_translate("MainWindow", "Movement Demonstrator"))
        self.pushButton.setText(_translate("MainWindow", "Click to Record"))

    def onButtonClick(self):
        global count
        count = count+1
        _translate = QtCore.QCoreApplication.translate
        screen_resolution = QtWidgets.QApplication.desktop().screenGeometry()
        width, height = screen_resolution.width(), screen_resolution.height()
        self.label2.setText(_translate("MainWindow", "Movement Follower"))
        self.label2.setGeometry(QtCore.QRect(width/2-width/4.8, height/2-height/8, width/2, height/8))
        if count==2:
            self.label.setText(_translate("MainWindow", "Your Final Score"))
            self.label.setGeometry(QtCore.QRect(width/2-width/10, height/2-height/4, width/2, height/8))
            code = random.randint(50, 90)
            self.label2.setText(_translate("MainWindow", str(code)))
            self.label2.setGeometry(QtCore.QRect(width/2-20, height/2-height/8, width/2, height/8))
            self.pushButton.setText(_translate("MainWindow", "Thank you"))
        if count==3:
            sys.exit(app.exec_())
        tt.run()



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
